// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXZ8OLxRCYdFlJ-hIC5x0VLmHwX9FDZKo',
    appId: '1:1003234632488:web:3019d012745f518c6ea61d',
    messagingSenderId: '1003234632488',
    projectId: 'libra-d612a',
    authDomain: 'libra-d612a.firebaseapp.com',
    storageBucket: 'libra-d612a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCisxB5ZnqySX3bklIVXKp94tBAQp-FEZY',
    appId: '1:1003234632488:android:172010e0386688f66ea61d',
    messagingSenderId: '1003234632488',
    projectId: 'libra-d612a',
    storageBucket: 'libra-d612a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlJHy7xVp_Z0lpN_lX8nwHwkC894uZ0wE',
    appId: '1:1003234632488:ios:e1a69f03f9c5aeb96ea61d',
    messagingSenderId: '1003234632488',
    projectId: 'libra-d612a',
    storageBucket: 'libra-d612a.appspot.com',
    androidClientId: '1003234632488-a9it1lt1acrp71nciekk8hn6211fo90u.apps.googleusercontent.com',
    iosClientId: '1003234632488-qeua9a3d58cbptkbdffp5d87vdqevhu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mouviMapApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe7_CZdlQGlJ3KgNbtPf5eAAdSU4gSHT8',
    appId: '1:1058376019036:ios:ef5e0b5845b68036ceca99',
    messagingSenderId: '1058376019036',
    projectId: 'mouvimap',
    databaseURL: 'https://mouvimap-default-rtdb.firebaseio.com',
    storageBucket: 'mouvimap.firebasestorage.app',
    iosBundleId: 'com.example.mouviMapApplication',
  );

}